(() => {
'use strict';
const STORAGE='pci_secundaria_aprende_v2_state_3';
const SOCIAL_NAMES=new Set(['Historia','Geografía','Formación Ética y Ciudadana','Economía']);
const NATURAL_NAMES=new Set(['Biología','Físico-Química','Física','Química']);
const ART_TERMS=new Set([1,2,3,4,7,8]);
const ORIENTATIONS=['Ciencias Naturales','Matemática y Física','Energía y Sustentabilidad','Economía y Administración','Educación Física','Comunicación','Literatura','Turismo','Lenguas','Informática','Educación','Ciencias Sociales y Humanidades','Arte - Artes Visuales','Arte - Música','Arte - Teatro','Agro y Ambiente'];
let DATA=null;
let state={schoolName:'Escuela Muestra',selected:['Economía y Administración'],active:'Economía y Administración',maps:{}};
let selectedSubject=null;
let currentProposalSlot=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const slug=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const levelForTerm=t=>Math.ceil(Number(t)/2);
const termsForYear=y=>[Number(y)*2-1,Number(y)*2];
function notify(msg,bad=false){const t=$('toast');t.textContent=msg;t.className='toast show'+(bad?' bad':'');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.className='toast',2300)}
function save(){state.schoolName=$('schoolName')?.value||state.schoolName;localStorage.setItem(STORAGE,JSON.stringify(state))}
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'null');if(raw&&raw.maps)state={...state,...raw}}catch{}}
function ensureMap(name){if(!state.maps[name])state.maps[name]={alt:'A',socialMode:'one',placements:{},teachers:'',validated:false,phase2:{}};const m=state.maps[name];m.placements=m.placements||{};m.phase2=m.phase2||{};m.socialMode=m.socialMode||'one';return m}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(id==='home')renderHome();if(id==='pciPanel')renderPanel();if(id==='phase1')renderPhase1();if(id==='phase2')renderPhase2()}
function fgSubjects(){const out=[];for(let y=1;y<=5;y++)for(const name of DATA.formacion_general[String(y)]||[])out.push({id:`fg-${y}-${slug(name)}`,name,year:y,origin:'FG'});return out}
function foSubjects(orientation){const d=DATA.formacion_orientada[orientation]||{};const m=ensureMap(orientation);const alt=d.sinAlternativas?'A':m.alt;const out=[];(d['3']||[]).forEach((name,i)=>out.push({id:`fo-${slug(orientation)}-3-${i}-${slug(name)}`,name,year:3,origin:'FO'}));for(const y of [4,5])((d[alt]||{})[String(y)]||[]).forEach((name,i)=>out.push({id:`fo-${slug(orientation)}-${y}-${i}-${slug(name)}`,name,year:y,origin:'FO'}));return out}
function allSubjects(){return [...fgSubjects(),...foSubjects(state.active)]}
function subjectById(id){return allSubjects().find(s=>s.id===id)||null}
function slotEntries(){const m=ensureMap(state.active);return Object.entries(m.placements).flatMap(([slot,ids])=>(ids||[]).map(id=>({slot,id})))}
function termOfSlot(slot){const m=slot.match(/-c(\d+)$/);return m?Number(m[1]):null}
function annualYearOfSlot(slot){const m=slot.match(/-n(\d+)$/);return m?Number(m[1]):null}
function usage(subjectId){const terms=new Set();for(const {slot,id} of slotEntries()){if(id!==subjectId)continue;const y=annualYearOfSlot(slot);if(y){termsForYear(y).forEach(t=>terms.add(t));continue}const t=termOfSlot(slot);if(t)terms.add(t)}return terms}
function usageText(s){const u=[...usage(s.id)].sort((a,b)=>a-b);return u.length?`${u.length}/2 · ${u.map(t=>'C'+t).join(', ')}`:'0/2'}
function renderHome(){$('schoolName').value=state.schoolName||'Escuela Muestra';const grid=$('orientationGrid');grid.innerHTML='';for(const o of ORIENTATIONS){const l=document.createElement('label');l.className='orientation-choice';l.innerHTML=`<input type="checkbox" ${state.selected.includes(o)?'checked':''}><span><strong>${esc(o)}</strong><small>Genera un PCI independiente</small></span>`;l.querySelector('input').onchange=e=>{if(e.target.checked){if(!state.selected.includes(o))state.selected.push(o);ensureMap(o);state.active=o}else{state.selected=state.selected.filter(x=>x!==o);if(state.active===o)state.active=state.selected[0]||null}save();renderHome()};grid.appendChild(l)}const pg=$('pciGrid');pg.innerHTML='';if(!state.selected.length){pg.innerHTML='<div class="notice warning">Elegí al menos una orientación para crear su PCI.</div>';return}for(const o of state.selected){const m=ensureMap(o);const card=document.createElement('article');card.className='card pci-card';card.innerHTML=`<p class="eyebrow">PCI independiente</p><h3>${esc(o)}</h3><span class="status ${m.validated?'ok':''}">${m.validated?'Mapa de la Oferta validado':'Mapa de la Oferta en construcción'}</span><button class="button primary">Abrir PCI</button>`;card.querySelector('button').onclick=()=>{state.active=o;save();showScreen('pciPanel')};pg.appendChild(card)}}
function renderPanel(){const m=ensureMap(state.active);$('pciTitle').textContent=`${state.schoolName} · ${state.active}`;$('pciSubtitle').textContent='Este PCI conserva sus propios agrupamientos, docentes y desarrollo curricular.';$('phase1Status').textContent=m.validated?'Validado':'En construcción';$('phase1Status').className='status'+(m.validated?' ok':'');$('openPhase2').disabled=!m.validated;$('phase2Card').classList.toggle('locked',!m.validated);$('phase2Status').textContent=m.validated?'Habilitado':'Requiere Fase 1';$('phase2Status').className='status '+(m.validated?'ok':'lock')}
function renderBag(){const m=ensureMap(state.active);$('bagTitle').textContent=state.active;const box=$('bagContent');let html='';for(let y=1;y<=5;y++){const list=fgSubjects().filter(s=>s.year===y);html+=`<section class="bag-year"><div class="bag-year-head"><strong>${y}.º año</strong><span>Nivel ${y} · C${y*2-1}/C${y*2}</span></div><div class="bag-subhead">Formación General</div>`;for(const s of list)html+=dragItemHTML(s);html+='</section>'}const fo=foSubjects(state.active);html+=`<section class="bag-year"><div class="bag-year-head"><strong>Formación Orientada</strong><span>3.º–5.º</span></div>`;const od=DATA.formacion_orientada[state.active]||{};if(!od.sinAlternativas)html+=`<div class="segmented" style="margin:8px 0 10px"><button data-alt="A" class="${m.alt==='A'?'active':''}">Alternativa A</button><button data-alt="B" class="${m.alt==='B'?'active':''}">Alternativa B</button></div>`;for(const y of [3,4,5]){html+=`<div class="bag-subhead">${y}.º año · Formación Orientada</div>`;for(const s of fo.filter(x=>x.year===y))html+=dragItemHTML(s)}html+='</section>';box.innerHTML=html;box.querySelectorAll('[data-subject]').forEach(el=>{el.addEventListener('dragstart',e=>{selectedSubject=el.dataset.subject;e.dataTransfer.setData('text/plain',selectedSubject)});el.onclick=()=>{selectedSubject=el.dataset.subject;box.querySelectorAll('.drag-item').forEach(x=>x.classList.toggle('selected',x===el));notify('Materia seleccionada. Tocá el espacio de destino.')}});box.querySelectorAll('[data-alt]').forEach(b=>b.onclick=()=>{m.alt=b.dataset.alt;m.validated=false;save();renderPhase1()})}
function dragItemHTML(s){return `<div class="drag-item" draggable="true" data-subject="${esc(s.id)}"><span class="grip">⠿</span><span><strong>${esc(s.name)}</strong><small>${s.year}.º · ${s.origin==='FG'?'Formación General':'Formación Orientada'}</small></span><span class="usage">${usageText(s)}</span></div>`}
function matrixRows(){return[{key:'trunk-lengua',label:'Lengua y Literatura',kind:'trunk'},{key:'trunk-matematica',label:'Matemática',kind:'trunk'},{key:'trunk-lengua-adicional',label:'Lengua Adicional',kind:'trunk'},{key:'naturales',label:'Laboratorios · Ciencias Naturales',kind:'quarter',active:t=>true},{key:'social-a',label:'Laboratorios · Ciencias Sociales A',kind:'quarter',active:t=>true},{key:'social-b',label:'Laboratorios · Ciencias Sociales B',kind:'quarter',active:t=>ensureMap(state.active).socialMode==='split'&&(t===5||t===6)},{key:'artes',label:'Talleres · Artes',kind:'quarter',active:t=>ART_TERMS.has(t)},{key:'tecnologias',label:'Talleres · Tecnologías',kind:'quarter',active:t=>true},{key:'educacion-fisica',label:'Talleres · Educación Física',kind:'quarter',active:t=>true},{key:'otros',label:'Otros formatos pedagógicos',kind:'quarter',active:t=>true},{key:'fo-general',label:'Formación Orientada · Espacios',kind:'quarter',active:t=>t>=5},{key:'fo3-art',label:'Nivel 3 · articulación FO + Sociales',kind:'quarter',active:t=>ensureMap(state.active).socialMode==='articulated'&&(t===5||t===6)}]}
function renderMatrix(){let html='<div class="level-strip"><div></div>';for(let y=1;y<=5;y++)html+=`<div class="level-head">Nivel ${y}</div>`;html+='</div><div class="term-strip"><div>Espacio</div>';for(let t=1;t<=10;t++)html+=`<div>C${t}</div>`;html+='</div>';for(const row of matrixRows()){html+=`<div class="matrix-row"><div class="row-label">${esc(row.label)}</div>`;if(row.kind==='trunk'){for(let y=1;y<=5;y++){const slot=`${row.key}-n${y}`;html+=`<div class="matrix-cell annual-slot"><div class="dropzone" data-slot="${slot}"><strong>Nivel ${y} · C${y*2-1}+C${y*2}</strong>${placedHTML(slot)}</div></div>`}}else{for(let t=1;t<=10;t++){if(row.active(t)){const slot=`${row.key}-c${t}`;html+=`<div class="matrix-cell"><div class="dropzone" data-slot="${slot}"><strong>${cellLabel(row.key,t)}</strong>${placedHTML(slot)}</div></div>`}else html+='<div class="matrix-cell inactive">—</div>'}}html+='</div>'}$('matrix').innerHTML=html;$('matrix').querySelectorAll('.dropzone').forEach(z=>{z.addEventListener('dragover',e=>{e.preventDefault();z.classList.add('ready')});z.addEventListener('dragleave',()=>z.classList.remove('ready'));z.addEventListener('drop',e=>{e.preventDefault();z.classList.remove('ready');const id=e.dataTransfer.getData('text/plain')||selectedSubject;if(id)assign(z.dataset.slot,id)});z.addEventListener('click',e=>{if(e.target.closest('[data-remove]'))return;if(selectedSubject)assign(z.dataset.slot,selectedSubject)})});$('matrix').querySelectorAll('[data-remove]').forEach(b=>b.onclick=e=>{e.stopPropagation();removeAssignment(b.dataset.slot,b.dataset.remove)})}
function cellLabel(key,t){if(key==='naturales')return`Laboratorio Natural · C${t}`;if(key==='social-a')return`Laboratorio Social A · C${t}`;if(key==='social-b')return`Laboratorio Social B · C${t}`;if(key==='artes')return`Taller de Artes · C${t}`;if(key==='tecnologias')return`Taller de Tecnologías · C${t}`;if(key==='educacion-fisica')return`Taller de Educación Física · C${t}`;if(key==='otros')return`Otro formato · C${t}`;if(key==='fo3-art')return`FO articulado · C${t}`;return`Espacio FO · C${t}`}
function placedHTML(slot){const ids=ensureMap(state.active).placements[slot]||[];return `<div class="drop-items">${ids.map(id=>{const s=subjectById(id);return s?`<div class="placed ${s.origin.toLowerCase()}">${esc(s.name)}<button data-remove="${esc(id)}" data-slot="${esc(slot)}">×</button></div>`:''}).join('')}</div>`}
function classify(s){if(SOCIAL_NAMES.has(s.name))return'social';if(NATURAL_NAMES.has(s.name))return'natural';if(s.name==='Artes')return'artes';if(['Educación Tecnológica','Tecnologías de la Información'].includes(s.name))return'tecnologias';if(s.name==='Educación Física')return'ef';if(['Lengua y Literatura','Matemática','Lengua Adicional'].includes(s.name))return'trunk';if(['Espacios de Definición Institucional','Tutoría'].includes(s.name))return'otros';return s.origin==='FO'?'fo':'other'}
function canAssign(slot,s){const yAnnual=annualYearOfSlot(slot),t=termOfSlot(slot),year=yAnnual||levelForTerm(t);if(s.year!==year)return[false,`Esta materia es de ${s.year}.º y el destino pertenece a ${year}.º.`];if(yAnnual){const expected=slot.startsWith('trunk-lengua-adicional')?'Lengua Adicional':slot.startsWith('trunk-lengua')?'Lengua y Literatura':'Matemática';if(s.name!==expected)return[false,`El espacio troncal ${expected} solo admite esa materia del mismo nivel.`]}if(t){const used=usage(s.id);if(used.has(t))return[false,`${s.name} ya está ubicada en C${t}. Al ser anual puede utilizarse una vez en cada cuatrimestre del nivel.`]}const c=classify(s);if(slot.startsWith('naturales-')&&!(c==='natural'||c==='fo'))return[false,'En Ciencias Naturales solo podés ubicar materias del campo natural y, desde Nivel 3, materializaciones FO cuando la regla lo permita.'];if(slot.startsWith('social-')&&c!=='social'&&c!=='fo')return[false,'En Ciencias Sociales solo podés ubicar materias sociales y, desde Nivel 3, materializaciones FO cuando la regla lo permita.'];if(slot.startsWith('artes-')&&c!=='artes')return[false,'Los talleres de Artes reciben la materia Artes del nivel correspondiente.'];if(slot.startsWith('tecnologias-')&&c!=='tecnologias')return[false,'Los talleres de Tecnologías reciben Educación Tecnológica / Tecnologías de la Información.'];if(slot.startsWith('educacion-fisica-')&&c!=='ef')return[false,'Los talleres de Educación Física reciben Educación Física.'];if(slot.startsWith('otros-')&&c!=='otros')return[false,'Este sector está destinado a otros formatos institucionales.'];if(slot.startsWith('fo-general-')&&s.origin!=='FO')return[false,'Este sector recibe materializaciones de Formación Orientada.'];if(slot.startsWith('fo3-art-')&&!(s.origin==='FO'||c==='social'))return[false,'La articulación de Nivel 3 recibe la materialización FO y una materia de Ciencias Sociales.'];return[true,'']}
function assign(slot,id){const s=subjectById(id);if(!s)return;const [ok,msg]=canAssign(slot,s);if(!ok){notify(msg,true);return}const m=ensureMap(state.active);m.placements[slot]=m.placements[slot]||[];if(!m.placements[slot].includes(id))m.placements[slot].push(id);m.validated=false;save();selectedSubject=null;renderPhase1();notify(`${s.name} ubicada.`)}
function removeAssignment(slot,id){const m=ensureMap(state.active);m.placements[slot]=(m.placements[slot]||[]).filter(x=>x!==id);m.validated=false;save();renderPhase1()}
function socialSet(slot){return new Set((ensureMap(state.active).placements[slot]||[]).map(subjectById).filter(Boolean).filter(s=>SOCIAL_NAMES.has(s.name)).map(s=>s.name))}
function foCount(slot){return(ensureMap(state.active).placements[slot]||[]).map(subjectById).filter(Boolean).filter(s=>s.origin==='FO').length}
function sameSet(a,b){return a.size===b.size&&[...a].every(x=>b.has(x))}
function socialValidation(){const m=ensureMap(state.active),mode=m.socialMode;const A5=socialSet('social-a-c5'),A6=socialSet('social-a-c6'),B5=socialSet('social-b-c5'),B6=socialSet('social-b-c6'),F5=socialSet('fo3-art-c5'),F6=socialSet('fo3-art-c6');const all4=new Set([...SOCIAL_NAMES]);if(mode==='one'){if(A5.size<4||A6.size<4)return{ok:false,msg:'En construcción: ubicá Historia, Geografía, FEC y Economía juntas en C5 y C6.'};if(!sameSet(A5,all4)||!sameSet(A6,all4))return{ok:false,msg:'El único laboratorio FG debe contener las cuatro materias sociales.'};return{ok:true,msg:'Válido: un laboratorio de Ciencias Sociales con las cuatro materias en C5 y C6.'}}if(mode==='split'){if(A5.size!==2||B5.size!==2||A6.size!==2||B6.size!==2)return{ok:false,msg:'En construcción: cada laboratorio A/B debe tener 2 materias en C5 y 2 en C6.'};const u5=new Set([...A5,...B5]),u6=new Set([...A6,...B6]);if(u5.size!==4||u6.size!==4)return{ok:false,msg:'Las cuatro materias deben repartirse sin repetirse entre A y B.'};const sig5=[[...A5].sort().join('|'),[...B5].sort().join('|')].sort().join('::');const sig6=[[...A6].sort().join('|'),[...B6].sort().join('|')].sort().join('::');if(sig5!==sig6)return{ok:false,msg:'Los agrupamientos 2+2 deben conservar la misma conformación en C5 y C6.'};return{ok:true,msg:'Válido: dos laboratorios 2+2 con agrupamientos consistentes en C5 y C6.'}}if(A5.size!==3||A6.size!==3||F5.size!==1||F6.size!==1)return{ok:false,msg:'En construcción: dejá 3 materias juntas en Sociales FG y 1 materia social dentro de la articulación FO, tanto en C5 como en C6.'};if(foCount('fo3-art-c5')<1||foCount('fo3-art-c6')<1)return{ok:false,msg:'La articulación necesita también la materialización de Formación Orientada de 3.º en C5 y C6.'};const u5=new Set([...A5,...F5]),u6=new Set([...A6,...F6]);if(u5.size!==4||u6.size!==4)return{ok:false,msg:'Las cuatro materias de Sociales deben quedar cubiertas exactamente una vez por cuatrimestre.'};if(!sameSet(A5,A6)||!sameSet(F5,F6))return{ok:false,msg:'La conformación del agrupamiento articulado debe mantenerse igual en C5 y C6.'};return{ok:true,msg:'Válido: una materia social articula con FO y las otras tres permanecen juntas en el laboratorio FG.'}}
function renderSocialControls(){const m=ensureMap(state.active);document.querySelectorAll('#socialModes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m.socialMode));const help={one:'Las 4 materias sociales quedan juntas en un único laboratorio FG. Debe repetirse la misma conformación en C5 y C6.',split:'Se habilita el Laboratorio Social B. Armá cualquier pareja 2+2; la misma pareja debe sostenerse en C5 y C6.',articulated:'Elegí 1 materia social para articular con la materialización FO de 3.º. Las otras 3 quedan juntas en el Laboratorio Social A.'};$('socialModeHelp').textContent=help[m.socialMode]}
function copySocial(){const m=ensureMap(state.active);for(const key of ['social-a','social-b','fo3-art'])m.placements[`${key}-c6`]=[...(m.placements[`${key}-c5`]||[])];m.validated=false;save();renderPhase1();notify('Composición de C5 copiada a C6.')}
function renderPhase1(){if(!state.active)return showScreen('home');const m=ensureMap(state.active);$('phase1Title').textContent=`${state.schoolName} · ${state.active}`;$('teachers').value=m.teachers||'';renderSocialControls();renderBag();renderMatrix();const v=socialValidation();$('validationMsg').textContent=v.msg;$('validationMsg').style.color=v.ok?'#156746':'#8a6414'}
function validateMap(){const m=ensureMap(state.active),v=socialValidation();if(!v.ok){notify(v.msg,true);return}m.validated=true;save();renderPhase1();notify('Mapa de la Oferta validado. Se habilitó el Mapa Propuesta Curricular.')}
function structuralSpaces(){const m=ensureMap(state.active),arr=[];for(const[slot,ids]of Object.entries(m.placements)){if(!ids?.length)continue;const names=ids.map(subjectById).filter(Boolean).map(s=>s.name);arr.push({slot,label:slotLabel(slot),subjects:names})}return arr.sort((a,b)=>a.label.localeCompare(b.label,'es'))}
function slotLabel(slot){const y=annualYearOfSlot(slot);if(y){if(slot.startsWith('trunk-lengua-adicional'))return`Lengua Adicional · Nivel ${y}`;if(slot.startsWith('trunk-lengua'))return`Lengua y Literatura · Nivel ${y}`;return`Matemática · Nivel ${y}`}const t=termOfSlot(slot),prefix=slot.split('-c')[0],labels={'naturales':'Laboratorio Ciencias Naturales','social-a':'Laboratorio Ciencias Sociales A','social-b':'Laboratorio Ciencias Sociales B','artes':'Taller de Artes','tecnologias':'Taller de Tecnologías','educacion-fisica':'Taller de Educación Física','otros':'Otro formato pedagógico','fo-general':'Espacio Formación Orientada','fo3-art':'Laboratorio FO articulado'};return`${labels[prefix]||prefix} · C${t}`}
function renderPhase2(){const m=ensureMap(state.active);if(!m.validated){notify('Primero tenés que validar el Mapa de la Oferta.',true);return showScreen('pciPanel')}$('phase2Title').textContent=`${state.schoolName} · ${state.active}`;const spaces=structuralSpaces();if(!currentProposalSlot||!spaces.some(s=>s.slot===currentProposalSlot))currentProposalSlot=spaces[0]?.slot||null;const box=$('proposalSpaces');box.innerHTML=spaces.length?spaces.map(s=>`<button class="proposal-space ${s.slot===currentProposalSlot?'active':''}" data-space="${esc(s.slot)}">${esc(s.label)}<br><small>${esc(s.subjects.join(' + '))}</small></button>`).join(''):'<p class="muted">Todavía no hay espacios con materias asignadas.</p>';box.querySelectorAll('[data-space]').forEach(b=>b.onclick=()=>{currentProposalSlot=b.dataset.space;renderPhase2()});renderProposalForm()}
function renderProposalForm(){const box=$('proposalFields');if(!currentProposalSlot){$('proposalSpaceTitle').textContent='Elegí un espacio';box.innerHTML='';return}const m=ensureMap(state.active),space=structuralSpaces().find(s=>s.slot===currentProposalSlot);$('proposalSpaceTitle').textContent=space?.label||currentProposalSlot;const d=m.phase2[currentProposalSlot]||{name:'',objectives:'',context:'',synopsis:'',deepening:'',plans:''};box.innerHTML=`<div class="readonly-source"><strong>Estructura heredada de Fase 1:</strong><br>${esc(space?.subjects.join(' + ')||'')}</div><div class="field-grid" style="margin-top:14px"><label><span>Nombre del espacio</span><input data-p2="name" value="${esc(d.name)}"></label><label><span>Contexto / práctica / eje</span><input data-p2="context" value="${esc(d.context)}"></label><label class="full"><span>Objetivos de aprendizaje</span><textarea data-p2="objectives">${esc(d.objectives)}</textarea></label><label class="full"><span>Sinopsis</span><textarea data-p2="synopsis">${esc(d.synopsis)}</textarea></label><label class="full"><span>Contenidos de profundización</span><textarea data-p2="deepening">${esc(d.deepening)}</textarea></label><label class="full"><span>Planes</span><textarea data-p2="plans">${esc(d.plans)}</textarea></label></div>`;box.querySelectorAll('[data-p2]').forEach(el=>el.oninput=()=>{const cur=m.phase2[currentProposalSlot]||{};cur[el.dataset.p2]=el.value;m.phase2[currentProposalSlot]=cur;save()})}
function openPrint(){const m=ensureMap(state.active);$('printModalTitle').textContent=`${state.schoolName} · ${state.active}`;const spaces=structuralSpaces();const rows=spaces.map(s=>`<tr><td>${esc(s.label)}</td><td>${esc(s.subjects.join(' + '))}</td></tr>`).join('');const developed=spaces.map(s=>{const d=m.phase2[s.slot]||{};return`<h3>${esc(d.name||s.label)}</h3><p><strong>Estructura:</strong> ${esc(s.subjects.join(' + '))}</p><p><strong>Objetivos:</strong> ${esc(d.objectives||'Pendiente')}</p><p><strong>Contexto / práctica:</strong> ${esc(d.context||'Pendiente')}</p><p><strong>Profundización:</strong> ${esc(d.deepening||'—')}</p><p><strong>Planes:</strong> ${esc(d.plans||'Pendiente')}</p>`}).join('');$('docPreview').innerHTML=`<h1>Proyecto Curricular Institucional</h1><p><strong>Escuela:</strong> ${esc(state.schoolName)}</p><p><strong>Orientación:</strong> ${esc(state.active)}</p><h2>Parte I · Mapa de la Oferta</h2><p><strong>Estado:</strong> ${m.validated?'Validado':'En construcción'}</p><table><thead><tr><th>Espacio</th><th>Materias / materializaciones</th></tr></thead><tbody>${rows||'<tr><td colspan="2">Sin asignaciones todavía.</td></tr>'}</tbody></table><h2>Parte II · Mapa Propuesta Curricular</h2>${developed||'<p>Pendiente de desarrollo.</p>'}`;$('printModal').classList.add('open')}
function downloadDoc(){const html=`<!doctype html><html><head><meta charset="utf-8"><title>PCI</title></head><body>${$('docPreview').innerHTML}</body></html>`;const blob=new Blob([html],{type:'application/msword'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PCI-${slug(state.schoolName)}-${slug(state.active)}.doc`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function init(){try{DATA=await fetch('data/materias-v2.json?v=20260910-2').then(r=>{if(!r.ok)throw new Error('No se pudo cargar materias-v2.json');return r.json()})}catch(err){document.body.innerHTML=`<main><div class="notice danger"><strong>Error cargando la base de materias.</strong><br>${esc(err.message)}</div></main>`;return}load();state.selected=state.selected.filter(o=>ORIENTATIONS.includes(o));if(!state.selected.length)state.selected=['Economía y Administración'];state.active=ORIENTATIONS.includes(state.active)?state.active:state.selected[0];state.selected.forEach(ensureMap);renderHome();$('schoolName').oninput=()=>{state.schoolName=$('schoolName').value;save();renderHome()};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showScreen(b.dataset.go));$('openPhase1').onclick=()=>showScreen('phase1');$('openPhase2').onclick=()=>showScreen('phase2');$('rulesBtn').onclick=()=>$('rulesModal').classList.add('open');$('printBtn').onclick=openPrint;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('open'));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});$('socialModes').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b)return;const m=ensureMap(state.active);m.socialMode=b.dataset.mode;m.validated=false;save();renderPhase1()};$('copySocialBtn').onclick=copySocial;$('validateBtn').onclick=validateMap;$('teachers').oninput=()=>{ensureMap(state.active).teachers=$('teachers').value;save()};$('browserPrint').onclick=()=>window.print();$('downloadDoc').onclick=downloadDoc}
init();
})();
